USE [master]
GO
/****** Object:  Database [Choferes]    Script Date: 7/7/2020 11:44:36 PM ******/
CREATE DATABASE [Choferes]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Choferes', FILENAME = N'E:\SQL 2019\MSSQL15.MSSQLSERVER01\MSSQL\DATA\Choferes.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Choferes_log', FILENAME = N'E:\SQL 2019\MSSQL15.MSSQLSERVER01\MSSQL\DATA\Choferes_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [Choferes] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Choferes].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Choferes] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Choferes] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Choferes] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Choferes] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Choferes] SET ARITHABORT OFF 
GO
ALTER DATABASE [Choferes] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Choferes] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Choferes] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Choferes] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Choferes] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Choferes] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Choferes] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Choferes] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Choferes] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Choferes] SET  ENABLE_BROKER 
GO
ALTER DATABASE [Choferes] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Choferes] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Choferes] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Choferes] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Choferes] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Choferes] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Choferes] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [Choferes] SET RECOVERY FULL 
GO
ALTER DATABASE [Choferes] SET  MULTI_USER 
GO
ALTER DATABASE [Choferes] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Choferes] SET DB_CHAINING OFF 
GO
ALTER DATABASE [Choferes] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [Choferes] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [Choferes] SET DELAYED_DURABILITY = DISABLED 
GO
EXEC sys.sp_db_vardecimal_storage_format N'Choferes', N'ON'
GO
ALTER DATABASE [Choferes] SET QUERY_STORE = OFF
GO
USE [Choferes]
GO
/****** Object:  Table [dbo].[Choferesruta]    Script Date: 7/7/2020 11:44:36 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Choferesruta](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Nombre] [varchar](15) NOT NULL,
	[Cedula] [int] NOT NULL,
	[Camion] [varchar](10) NOT NULL,
	[Ciudad] [varchar](15) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Registrarcamion]    Script Date: 7/7/2020 11:44:36 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Registrarcamion](
	[ID_camion] [int] IDENTITY(1,1) NOT NULL,
	[Placa] [int] NOT NULL,
	[Marca] [varchar](15) NULL,
	[Modelo] [varchar](15) NULL,
	[Año] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID_camion] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Registrarciudad]    Script Date: 7/7/2020 11:44:36 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Registrarciudad](
	[ID_ciudad] [int] IDENTITY(1,1) NOT NULL,
	[Ciudad] [varchar](15) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID_ciudad] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Users]    Script Date: 7/7/2020 11:44:36 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Users](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Username] [varchar](15) NOT NULL,
	[Passwords] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET IDENTITY_INSERT [dbo].[Choferesruta] ON 
GO
INSERT [dbo].[Choferesruta] ([ID], [Nombre], [Cedula], [Camion], [Ciudad]) VALUES (3, N'Oliver Gomez', 4022652, N'25130220', N'Santo Domingo')
GO
INSERT [dbo].[Choferesruta] ([ID], [Nombre], [Cedula], [Camion], [Ciudad]) VALUES (5, N'Steven Mcbrum', 4026985, N'2514', N'Samana')
GO
SET IDENTITY_INSERT [dbo].[Choferesruta] OFF
GO
SET IDENTITY_INSERT [dbo].[Registrarcamion] ON 
GO
INSERT [dbo].[Registrarcamion] ([ID_camion], [Placa], [Marca], [Modelo], [Año]) VALUES (5, 2514, N'XS', N'XSS', 2018)
GO
INSERT [dbo].[Registrarcamion] ([ID_camion], [Placa], [Marca], [Modelo], [Año]) VALUES (6, 25130220, N'Akbhar', N'Bomb', 2020)
GO
SET IDENTITY_INSERT [dbo].[Registrarcamion] OFF
GO
SET IDENTITY_INSERT [dbo].[Registrarciudad] ON 
GO
INSERT [dbo].[Registrarciudad] ([ID_ciudad], [Ciudad]) VALUES (1, N'Santo Domingo')
GO
INSERT [dbo].[Registrarciudad] ([ID_ciudad], [Ciudad]) VALUES (3, N'Samana')
GO
SET IDENTITY_INSERT [dbo].[Registrarciudad] OFF
GO
SET IDENTITY_INSERT [dbo].[Users] ON 
GO
INSERT [dbo].[Users] ([ID], [Username], [Passwords]) VALUES (1, N'Oliver25', 25130220)
GO
SET IDENTITY_INSERT [dbo].[Users] OFF
GO
USE [master]
GO
ALTER DATABASE [Choferes] SET  READ_WRITE 
GO
